server:
  port: 7009
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.114:8848
#    sentinel:
#      transport:
#        dashboard: 127.0.0.1:9500
#        port: 8719
  application:
    name: mall-miaosha
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.1.118
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.1.114
    port: 5672
    virtual-host: /
task:
  seckill: 0 0/30 0 * * ? #每天24点执行一次
