server:
  port: 7009
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.114:8848
    sentinel:
      transport:
        dashboard: 192.168.1.118:9500
        port: 8719
  application:
    name: mall-miaosha
  zipkin:
    base-url: 192.168.1.114:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    url: jdbc:mysql://192.168.1.118:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.1.118
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 192.168.1.114
    port: 5672
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    #手动ack
    template:
      mandatory: true
    listener:
      direct:
        acknowledge-mode: manual
task:
  seckill: 0 12 17 * * ? #每天24点执行一次
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
management:
  endpoints:
    web:
      exposure:
        include: '*'

mall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
