server:
  port: 7002
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.118:3306/mall_ums?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: mall-member
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
logging:
  level:
    com.qiangzengy.mall: debug