server:
  port: 7001
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.118:3306/mall_sms?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.114:8848
    sentinel:
      transport:
        dashboard: 192.168.1.118:9500
  application:
    name: mall-coupon
  zipkin:
    base-url: 192.168.1.114:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.qiangzengy.mall: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'