server:
  port: 10000
#spring session的过期时间
  servlet:
    session:
      timeout: 30m
spring:
  application:
    name: mall-auth
  zipkin:
    base-url: 192.168.1.114:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 192.168.1.118:9500
  thymeleaf:
    cache: false
  redis:
    host: 192.168.1.118
    port: 6379
#spring session
  session:
    store-type: redis

weibo:
  oauth:
    client_id: 2636917288
    client_secret: a263e9284c6c1a74a62adacs11b6e2
    grant_type: authorization_code
    redirect_uri: http://gulimall.com/oauth2/weibo/success

management:
  endpoints:
    web:
      exposure:
        include: '*'