server:
  port: 8001
  servlet:
    session:
      timeout: 30
spring:
  application:
    name: mall-es
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.114:8848
  redis:
    host: 192.168.1.118
  session:
    store-type: redis
mall:
  elasticsearch:
    ip_address: 192.168.1.114