server:
  port: 8001
  servlet:
    session:
      timeout: 30
spring:
  application:
    name: mall-es
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.3.42
  session:
    store-type: redis