server:
  port: 9100
spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    access-id: LTAIp7GR######
    access-key: j67w1pI66O57#######
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: mall-data