server:
  port: 9100
spring:
  application:
    name: mall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  oss:
    access-id: LTAI4GHjUaiNivvibrySo9rW
    access-key: 67Y2fT4JCMPGkttQXFhn8tQrdU1M7g
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: mall-data